spec:
  replicaCount: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate

image:
  repository: localhost:32000/my-cv
  pullPolicy: Always
  tag: develop

deployment:
  containerPort: 80
  containerProtocol: TCP

lifecycle:
  enable: "false"

service:
  name: web
  port: 80
  targetPort: 80
  nodePort: 30080

resources:
  requests:
    cpu: 0.25
    memory: 200Mi
  limits:
    cpu: 025
    memory: 200Mi
